version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      awscli:
        applies-to: version-updates
        patterns:
          - "awscli"
          - "botocore"
        update-types:
          - "minor"
          - "patch"
