name: Docker Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                platform: [
                    "linux/amd64",
#                    "linux/arm64"
                ]
                tag: [
                    1.15-alpine,
                    1.16-alpine,
                    1.17-alpine-v1,
                    1.17-alpine-v2,
                    1.17-alpine-v3,
                    1.17-alpine-v4,
                    1.17-alpine-v5,
                    1.17-alpine-v6,
                    1.17-alpine-v7,
                    1.17-alpine-v8,
                    1.17-alpine-v9,
                    1.17-alpine-v10,
                    1.17-alpine-v11,
                    1.18-alpine,
                    1.19-alpine,
                    1.20-alpine,
                    1.21-alpine,
                    1.22-alpine,
                    1.23-alpine,
                    1.24-alpine,
                    1.25-alpine,
                    1.26-alpine,
                    1.27-alpine,
                ]

        name: ${{ matrix.tag }} | ${{ matrix.platform }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install Docker buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v3
                with:
                    version: latest

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Image
                run: sh build.sh ${{ matrix.tag }} ${{ matrix.platform }}

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'
